S (S#, SNOMBRE, SITUACIÓN, CIUDAD )
P (P#, PNOMBRE, COLOR, PESO, CIUDAD)
J (J#, JNOMBRE, CIUDAD)
SPJ (S#, P#, J#, CANT )

-- Consultas sencillas
-- 1 
SELECT * FROM J;

-- 2
SELECT * FROM J
WHERE CIUDAD = 'Londres';

-- 3
SELECT DISTINCT S# FROM SPJ
WHERE J# = 'J1'
ORDER BY S#;

-- 4
SELECT * FROM SPJ
WHERE 300 <= CANT AND CANT <= 750;

-- 5
SELECT DISTINCT COLOR, CIUDAD FROM P;

-- Reuniones (Join)
-- 6
SELECT S#, P#, J# FROM S, P, J
WHERE S.CIUDAD = P.CIUDAD AND P.CIUDAD = J.CIUDAD;

-- 7
SELECT S#, P#, J# FROM S, P, J
WHERE NOT (S.CIUDAD = P.CIUDAD AND P.CIUDAD = J.CIUDAD);

-- 8
SELECT S#, P#, J# FROM S, P, J
WHERE S.CIUDAD <> P.CIUDAD 
AND P.CIUDAD <> J.CIUDAD 
AND S.CIUDAD <> J.CIUDAD;

-- 9
SELECT DISTINCT P# FROM SPJ, S
WHERE SPJ.S# = S.S# AND S.CIUDAD = 'Londres';

-- 10
SELECT P# FROM SPJ, S#, J#
WHERE SPJ.S# = S.S# AND S.CIUDAD = 'Londres'
AND SPJ.J# = J.J# AND J.CIUDAD = 'Londres';

-- 11
SELECT DISTINCT S.CIUDAD, J.CIUDAD FROM SPJ, S, J
WHERE SPJ.S# = S.S# AND SPJ.J# = J.J#;

-- 12
SELECT DISTINCT P# FROM SPJ, S#, J#
WHERE SPJ.S# = S.S# AND SPJ.J# = SPJ.J#
AND S.CIUDAD = J.CIUDAD;

-- 13
SELECT DISTINCT J# FROM SPJ, S#, J#
WHERE SPJ.S# = S.S# AND SPJ.J# = J.J#
AND S.CIUDAD <> J.CIUDAD;

-- 14
SELECT DISTINCT SPJ1.P#, SPJ2.P# FROM SPJ SPJ1, SPJ SPJ2
WHERE SPJ1.S# = SPJ2.S# AND SPJ1.P# < SPJ2.P#;

-- Funciones de agregados
-- 15
SELECT COUNT (DISTINCT J#) FROM SPJ
WHERE S# = 'S1';

-- 16 
SELECT SUM(CANT) FROM SPJ
WHERE P# = 'P1' AND S# = 'S1';

-- 17
SELECT P#, J#, SUM(CANT) FROM SPJ
GROUP BY P#, J#;

-- 18
SELECT P#, J#, SUM(CANT) FROM SPJ
GROUP BY P#, J#
HAVING AVG(CANT) > 320;

-- Diversas
-- 19
SELECT * FROM SPJ
WHERE CANT IS NOT NULL;

--20
SELECT J#, CIUDAD FROM J
WHERE CIUDAD LIKE '_o%';

-- Subconsultas
-- 21
SELECT JNOMBRE FROM J
WHERE J.J# IN (SELECT SPJ.J# FROM SPJ
               WHERE SPJ.S# = 'S1');

-- 22
SELECT DISTINCT COLOR FROM P
WHERE P.P# IN (SELECT SPJ.P# FROM SPJ
               WHERE SPJ.S# = 'S1'); 

-- 23
SELECT DISTINCT P# FROM SPJ
WHERE SPJ.J# IN (SELECT J.J# FROM J
                 WHERE CIUDAD = 'Londres'); 

-- 24
SELECT DISTINCT J# FROM SPJ
WHERE P# IN (SELECT P# FROM SPJ
            WHERE S# = 'S1'); 

-- 25
SELECT DISTINCT S# FROM SPJ
WHERE P# IN (SELECT P# FROM SPJ 
             WHERE S# IN (SELECT S# FROM SPJ
                          WHERE P# IN (SELECT P# FROM P
                                       WHERE COLOR = 'Rojo')));

-- 26
SELECT S# FROM S
WHERE SITUACION < (SELECT SITUACION FROM S
                   WHERE S# = "S1");

-- 27
SELECT J# FROM 
WHERE CIUDAD = (SELECT MIN(CIUDAD) FROM J);

-- EXISTS
-- 28
SELECT DISTINCT P# FROM SPJ
WHERE EXISTS (SELECT * FROM J
              SPJ.J# = J.J# AND CIUDAD = 'Londres');

-- 29
SELECT DISTINCT J# FROM SPJ SPJ1
WHERE EXISTS (SELECT * FROM SPJ SPJ2
              WHERE SPJ2.S# = 'S1' AND SPJ1.P# = SPJ2.P#); 

-- 30
SELECT DISTINCT J# FROM SPJ
WHERE NOT EXISTS (SELECT * FROM SPJ
                  WHERE J# = J.#
                  AND P# IN (SELECT P# FROM P
                             WHERE COLOR = 'Rojo')
                  AND S# IN (SELECT S# FROM S
                             WHERE CIUDAD = 'Londres'));

-- 31 
SELECT DISTINCT J# FROM SPJ SPJ1
WHERE NOT EXISTS (SELECT * FROM SPJ SPJ2
                  WHERE SPJ1.J# = SPJ2.J# AND SPJ2.S# == 'S1');

-- Unión
-- 32
SELECT CIUDAD FROM S
UNION
SELECT CIUDAD FROM P
UNION
SELECT CIUDAD FROM J
ORDER BY 1;

-- Operaciones de actualización
-- 33
UPDATE P
SET COLOR = 'Gris'
WHERE COLOR = 'Rojo';

-- 34
DELETE FROM J
WHERE J# NOT IN (SELECT J# FROM SPJ);

-- 35
INSERT INTO S VALUES ('S10', 'Salazar', NULL, 'Nueva York');