-- Parte I
COMPETICION (P#, DESCRIPCION, CATEGORIA)
CLUB (C#, NOM_C, PRESUPUESTO)
PARTICIPACION (C#, P#, PUESTO)

-- 1
SELECT NOM_C FROM CLUB
WHERE PRESUPUESTO > 2000000
AND C# IN (SELECT C# FROM PARTICIPACION
           WHERE P# IN (SELECT P# FROM COMPETICION
                        WHERE CATEGORIA = 2));

-- 2
SELECT NOM_C FROM CLUB
WHERE C# IN (SELECT C# FROM PARTICIPACION
             WHERE PUESTO = 1)
AND C# NOT IN (SELECT C# FROM PARTICIPACION
               WHERE PUESTO > 1);

-- 3
SELECT NOM_C FROM CLUB
WHERE C# IN (SELECT C# FROM PARTICIPACION
             GROUP BY C#
             HAVING COUNT (DISTINCT P#) = (SELECT COUNT(P#) FROM COMPETICION));
-- 3 Alternativo
SELECT NOM_C FROM CLUB
WHERE NOT EXISTS (SELECT P# FROM COMPETICION
                  WHERE NOT EXISTS (SELECT * FROM PARTICIPACION
                                    WHERE PARTICIPACION.P# = COMPETICION.P#
                                    AND PARTICIPACION.C# = CLUB.C#));

-- 4
SELECT NOM_C FROM CLUB
WHERE C# IN (SELECT C# FROM PARTICIPACION
             WHERE P# = 'P1')
AND C# IN (SELECT C# FROM PARTICIPACION
           WHERE P# = 'P2');

-- 5
SELECT NOM_C, PRESUPUESTO FROM CLUB
WHERE C# NOT IN (SELECT C# FROM PARTICIPACION
                 WHERE PUESTO = 1);

--------------------------------------------------------------------------------

-- Parte II
JUGADORES (J#, NOMBRE, NACIONALIDAD)
CAMPEONATOS (C#, CNOMBRE, CATEGORIA)
PARTIDAS (P#, J1#, J2#, C#, FECHA, RESULTADO)

-- 1
SELECT DISTINCT PARTIDAS.P#, FECHA, RESULTADO FROM PARTIDAS, CAMPEONATOS
WHERE PARTIDAS.C# = CAMPEONATOS.C# AND CAMPEONATOS.CATEGORIA = 'Junior'
AND (PARTIDAS.J1# IN (SELECT J# IN JUGADORES WHERE NACIONALIDAD = 'Argentina')
     OR PARTIDAS.J2# (SELECT J# IN JUGADORES WHERE NACIONALIDAD = 'Argentina'));

-- 2
SELECT NOMBRE FROM JUGADORES
WHERE EXISTS (SELECT * FROM PARTIDAS
              WHERE (JUGADORES.J# = PARTIDAS.J1# OR JUGADORES.J# = PARTIDAS.J2#)
              AND (PARTIDAS.C# = 'C1' OR PARTIDAS.C# = 'C7'));

-- 3
SELECT NOMBRE FROM JUGADORES
WHERE EXISTS (SELECT * FROM PARTIDAS
              WHERE (JUGADORES.J# = PARTIDAS.J1# OR JUGADORES.J# = PARTIDAS.J2#)
              AND PARTIDAS.C# = 'C1')
AND EXISTS (SELECT * FROM PARTIDAS
              WHERE (JUGADORES.J# = PARTIDAS.J1# OR JUGADORES.J# = PARTIDAS.J2#)
              AND PARTIDAS.C# = 'C7');

-- 4
SELECT CAMPEONATOS.C# FROM CAMPEONATOS, PARTIDAS, JUGADORES J1, JUGADORES J2
WHERE CAMPEONATOS.C# = PARTIDAS.C# AND PARTIDAS.J1# = J1.J# 
AND PARTIDAS.J2# = J2.J# AND J1.NACIONALIDAD = J2.NACIONALIDAD;

-- 5
WHERE NOMBRE FROM JUGADORES
WHERE NOT EXISTS (SELECT * FROM PARTIDAS
                  WHERE JUGADORES.J# = PARTIDAS.J1# AND JUGADORES.J# = PARTIDAS.J2#);

--------------------------------------------------------------------------------

-- Parte III
PERSONA(Nombre, Sexo, FechaNac, NombreMadre, NombrePadre)
MATRIMONIO(NombreMujer, NombreVaron, FechaRealizacion, FechaFin)

