-- Parte 1
SOCIO (AFICIONADO, VIDEOCLUB)
GUSTA (AFICIONADO, PELICULA)
VIDEOTECA (VIDEOCLUB, PELICULA)

-- a
SELECT VIDEOCLUB FROM VIDEOTECA
WHERE PELICULA IN (SELECT PELICULA FROM GUSTA
                   WHERE GUSTA.AFICIONADO = 'José Pérez');

-- b
SELECT DISTINCT SOCIO.AFICIONADO FROM SOCIO, GUSTA, VIDEOTECA
WHERE SOCIO.AFICIONADO = GUSTA.AFICIONADO AND SOCIO.VIDEOCLUB = VIDEOTECA.CLUB
AND GUSTA.PELICULA = VIDEOTECA.PELICULA;

-- c
SELECT DISTINCT AFICIONADO FROM SOCIO
WHERE NOT EXISTS (SELECT * FROM VIDEOTECA, GUSTA
                  WHERE VIDEOTECA.PELICULA = GUSTA.PELICULA
                  AND SOCIO.AFICIONADO = GUSTA.AFICIONADO
                  AND SOCIO.VIDEOCLUB = VIDEOTECA.VIDEOCLUB);

-- d
SELECT DISTINCT VIDEOCLUB FROM VIDEOTECA
WHERE PELICULA = 'A'
AND VIDEOCLUB IN (SELECT VIDEOCLUB FROM VIDEOTECA
                  WHERE PELICULA = 'B');

-- e
SELECT DISTINCT AFICIONADO FROM SOCIO
GROUP BY AFICIONADO
HAVING (SELECT COUNT(DISTINCT VIDEOCLUB) FROM VIDEOTECA, GUSTA
        WHERE GUSTA.AFICIONADO = SOCIO.AFICIONADO
        AND GUSTA.PELICULA = VIDEOTECA.PELICULA
        AND SOCIO.VIDEOCLUB = VIDEOTECA.VIDEOCLUB) >= 2;

--------------------------------------------------------------------------------

-- Parte 2
EDITORIALES (EDITORIAL#, NOMBRE, CIUDAD)
LIBROS (LIBRO#, TITULO, AUTOR, AÑO)
LIBRERIAS (LIBRERIA#, NOMBRE, CIUDAD)
ELL (EDITORIAL#, LIBRO#, LIBRERIA#, CANTIDAD)

-- a
SELECT DISTINCT NOMBRE FROM LIBRERIAS
WHERE LIBRERIA# IN (SELECT LIBRERIA# FROM ELL
                    WHERE EDITORIAL# IN (SELECT EDITORIAL# FROM EDITORIALES
                                         WHERE EDITORIAL.CIUDAD = 'Rosario'));

-- b
SELECT DISTINCT EDITORIAL# FROM ELL
WHERE LIBRERIA# = 'P1'
AND EDITORIAL# IN (SELECT EDITORIAL# FROM ELL
                   WHERE LIBRERIA# = 'P2');

-- c
SELECT DISTINCT LIBRERIA# FROM LIBRERIAS
WHERE (SELECT COUNT(DISTINCT EDITORIAL#) FROM ELL
       WHERE ELL.LIBRERIA# = LIBRERIAS.LIBRERIA#)
       =
       (SELECT COUNT(*) FROM EDITORIALES);

-- c alternativo
SELECT Libreria# FROM Librerías, ELL
WHERE Librerias.Liberia# = ELL.Libreria#
GROUP BY Libreria#
HAVING COUNT(DISTINCT Editorial#) = (SELECT COUNT(Editorial#) FROM Editoriales);

--------------------------------------------------------------------------------

-- Parte 3
GUIAS (COD-GUIA, NOMBRE, DIRECCION, TELEFONO)
COTOS (COD-COTO, NOMBRE, EXTENSION)
ESPECIES (COD-ESPECIE, NOMBRE, FECHA-INICIO-VEDA, FECHA-FIN-VEDA)
PARTIDA (COD-GUIA, COD-COTO, COD-ESPECIE, FECHA, NUMERO_PIEZAS)

-- a
SELECT NOMBRE, DIRECCION FROM GUIAS
WHERE COD-GUIA NOT IN (SELECT CODGUIA FROM PARTIDA);

-- b
SELECT NOMBRE FROM GUIAS
WHERE COD-GUIA IN (SELECT CODGUIA FROM PARTIDA
                   WHERE COD-COTO <> 'C3' AND COD-COTO <> 'C7');

-- c
SELECT NOMBRE FROM GUIAS
WHERE COD-GUIA IN (SELECT CODGUIA FROM PARTIDA
                   WHERE COD-COTO == 'C1')
AND COD-GUIA IN (SELECT CODGUIA FROM PARTIDA
                 WHERE COD-COTO == 'C5');

-- d
SELECT NOMBRE FROM COTOS
WHERE NOT EXISTS (SELECT * FROM ESPECIES
                  WHERE COD-ESPECIE NOT IN (SELECT COD-ESPECIE FROM PARTIDA
                                            WHERE PARTIDA.COD-COTO = COTOS.COD-COTO));

--------------------------------------------------------------------------------

-- Parte 4
ALUMNOS (A#, NOMBRE, GRUPO)
PRACTICAS (P#, CURSO, FECHA)
ENTREGA (A#, P#, NOTA)

-- a
SELECT NOMBRE FROM ALUMNOS
WHERE GRUPO = 'C' OR GRUPO = 'F';

-- b
SELECT NOMBRE FROM ALUMNOS
WHERE NOT EXISTS (SELECT * FROM PRACTICAS
                  WHERE CURSO = 3
                  AND P# NOT IN (SELECT P# FROM ENTREGAS
                                 WHERE ENTREGA.A# = ALUMNOS.A#));

-- c
SELECT NOMBRE FROM ALUMNOS
WHERE A# IN (SELECT A# FROM ENTREGA
             WHERE P# IN (SELECT P# FROM PRACTICAS
                          WHERE CURSO = 2))
AND A# IN (SELECT A# FROM ENTREGA
           WHERE P# IN (SELECT P# FROM PRACTICAS
                        WHERE CURSO = 3));

-- d
SELECT NOMBRE FROM ALUMNOS
WHERE A# NOT IN (SELECT A# FROM ENTREGA
                 WHERE P# IN (SELECT P# FROM PRACTICAS
                              WHERE CURSO <> 2))
AND A# IN (SELECT A# FROM ENTREGA
           WHERE P# IN (SELECT P# FROM PRACTICAS
                        WHERE CURSO = 2));

-- e
SELECT NOMBRE FROM ALUMNOS
WHERE GRUPO = (SELECT GRUPO FROM ALUMNOS
               WHERE A# = 'A25')
AND A# <> 'A25';

-- f
SELECT NOMBRE FROM ALUMNOS
WHERE A# NOT IN (SELECT DISTINCT A# FROM ENTREGA);